resume: #ckpt/best/model_best.pth
save_ckpt_dir: ckpt/
log_tensor_dir: tensorboard/ #tensorboard --logdir=./tensorboard --port 8123
device:
cpus:
metrics:
  - _target_: model.metric.accuracy
  - _target_: model.metric.top_k_acc

defaults:
  - _self_
  - data: mnist_train
  - model: mnist_lenet
  - hparams: lenet_baseline
  - status: train
  - hydra/run/dir: job_timestamp
  - override hydra/job_logging: custom
